### ISSUE TITLE
Exception handled via LogInformation instead of LogError

### ISSUE THREAD

**Issue by sunnamed434** [DbUp/dbup-mysql#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Library Version

6.0.1-beta.41

### What happened?

The problem can be seen [here](https://github.com/DbUp/dbup-mysql/blob/461bd38efab2e294d60bbba76fdb39443f48a45b/src/dbup-mysql/MySqlExtensions.cs#L167), is [LogInformation](https://github.com/DbUp/DbUp/blob/b07bb780600dea7f1452adf6208d3e2111e9880b/src/dbup-core/Engine/Output/IUpgradeLog.cs#L28) intended instead of using [LogError(exception, ..)](https://github.com/DbUp/DbUp/blob/b07bb780600dea7f1452adf6208d3e2111e9880b/src/dbup-core/Engine/Output/IUpgradeLog.cs#L48) ? I guess it was not updated because dbup-mysql moved to Microsoft logging style, in my case it's problematic because: I can't handle this exception, I have to create own implementation of logger and check if `format` argument is a `Database not found on server with connection string in settings`, instead I want to fail my app by handling this exception (for example re-throwing the exception) and outputting more information about what happened.

### Relevant log output

```shell
2024-07-28 21:15:02 Database not found on server with connection string in settings: Unable to connect to any of the specified MySQL hosts.
2024-07-28 21:15:02 Unhandled exception. MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
2024-07-28 21:15:02  ---> System.Net.Sockets.SocketException (111): Connection refused
2024-07-28 21:15:02    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2024-07-28 21:15:02    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2024-07-28 21:15:02    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
2024-07-28 21:15:02 --- End of stack trace from previous location ---
2024-07-28 21:15:02    at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.NativeDriver.<>c.<OpenAsync>b__38_0(Exception ex)
2024-07-28 21:15:02    at System.AggregateException.Handle(Func`2 predicate)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.NativeDriver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.Driver.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.Driver.CreateAsync(MySqlConnectionStringBuilder settings, Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlPool.GetPooledConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlPool.TryToGetDriverAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlPool.GetConnectionAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Boolean execAsync, CancellationToken cancellationToken)
2024-07-28 21:15:02    at MySql.Data.MySqlClient.MySqlConnection.Open()
2024-07-28 21:15:02    at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString, IUpgradeLog logger, Int32 timeout, String collation) in /_/src/dbup-mysql/MySqlExtensions.cs:line 172
2024-07-28 21:15:02    at MySqlExtensions.MySqlDatabase(SupportedDatabasesForEnsureDatabase supported, String connectionString) in /_/src/dbup-mysql/MySqlExtensions.cs:line 98
2024-07-28 21:15:02    at UnturnedGuardAPI.App.Configurations.DependencyInjection.PrepareDatabases(IConfiguration configuration) in /src/src/UnturnedGuardAPI.App/Configurations/DependencyInjection.cs:line 28
2024-07-28 21:15:02    at Program.<Main>$(String[] args) in /src/src/UnturnedGuardAPI.App/Program.cs:line 5
2024-07-28 21:15:02    at Program.<Main>(String[] args)
```

**Comment by droyad** [comment]
I splunked a bit and it has been this way [since the original PR](https://github.com/DbUp/DbUp/pull/454/files#diff-4908c6d5cf25bb4b6ce25383d5c159b11a7c08dc2f8a4efbf78329b467ead76dR168).

I _think_ we should throw an exception here. I'm not that familiar with MySQL.

Is there any case we get to that point and everything is ok except for the database not existing? The `DatabaseExists` code looks like it should work without exception. When does it throw an exception?

**Comment by sunnamed434** [comment]
> I think we should throw an exception here. I'm not that familiar with MySQL.

Yep, I do agree about that. 👍 

> Is there any case we get to that point and everything is ok except for the database not existing? The DatabaseExists code looks like it should work without exception. When does it throw an exception?

It throws an exception if it can't connect to the database
